require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.telescope"
require "user.bufferline"
require "user.autopairs"
require "user.cmp"
require "user.treesitter"
require "user.lualine"
require "user.gitsigns"
require "user.lspsaga"
require "user.lsp.mason"
require "user.telescope-file-browser"
require "user.null-ls"
--[[
require "user.autocommands"
require "user.nvim-tree"
require "user.indentline"
require "user.transparent"
--require "user.feline"
require "user.colorizer"
require "user.prettier"
]]--
